### ISSUE TITLE
Live gold maximum 2b 

### ISSUE THREAD

**Issue by kotsh23** [JellyBitz/vSRO-ServerAddon#1]
Hello i tried to give my self gold 3b for Example

`INSERT INTO [SRO_VT_SHARD].[dbo].[_ExeGameServer]
(
	Action_ID,
	CharName16,
	Param02 -- Gold Offset
)
VALUES
(
	2,
	'DsCor',
	3000000000 -- Increase by 3b
);`

But i get no thing and action_result 4 

i hope if you can make it accept more than int

**Comment by JellyBitz** [comment]
v1.0.1.0 should solve this issue.

**Comment by kotsh23** [comment]
Thank you for your quick fix its working fine 
but i have 1 question .
when i try to send 3b for example its sent successfully 
but ingame client showing 2147483647 gold gained which is int maximum value

its cant be fix somehow ? 
Thank you

**Comment by JellyBitz** [comment]
Looks like the datatype it's not a `long` but `int`, I'll check futher.

---
Oh.. this is just visual. It's something that cannot be fixed from DLL actually. It will requires client side edition.
I'll try to check anyways :ok_hand:

**Comment by JellyBitz** [comment]
The message about gold received "2147483647" is a client side data type restriction (`uint`).
Not easy to change as far as I know..

So the message has been removed at `v1.0.2.0`, but only if the gold exceed this value to avoid sent a wrong message to the player.

 If you can deal with the data type issue, feel free to re open this issue. :ok_hand:
