### ISSUE TITLE
EU mastery skills max 240

### ISSUE THREAD

**Issue by kotsh23** [JellyBitz/vSRO-ServerAddon#10]
Hello 
If you change max level to 140 and CH mastery to 420 , eu mastery will stuck at 240

**Comment by kotsh23** [comment]
@JellyBitz 
any idea how to fix this boss ?

**Comment by JellyBitz** [comment]
Added EU mastery as an option.. Let me to know if works for you to close this issue.

**Comment by kotsh23** [comment]
how i can add it and where

في الاثنين، ١٧ أبريل ٢٠٢٣, ٥:١٥ ص Engels Quintero ***@***.***>
كتب:

**Comment by JellyBitz** [comment]
Update and compile the project. You'll get the changes with the new dll generated.
