### ISSUE TITLE
New Release doesn't have vSRO-GameServer.ini  

### ISSUE THREAD

**Issue by kotsh23** [JellyBitz/vSRO-ServerAddon#3]
Hello Boss!
the new features have to edit new lines at vSRO-GameServer.ini or Shard ini ?

**Comment by JellyBitz** [comment]
Latest release (v1.0.3.0) has all the files and includes the config file for every DLL which is auto generated also if no config file exist.

---
It's like any file update, replace the old ones with the new ones.

**Comment by kotsh23** [comment]
i checking the new clone of project now i cant find any ini files

**Comment by JellyBitz** [comment]
To clarify, cloning the project will not give you the auto generated files.

All files are attached with the binaries (.bin.zip)
https://github.com/JellyBitz/vSRO-ServerAddon/releases
