### ISSUE TITLE
Unique Kill message not working

### ISSUE THREAD

**Issue by carlos-pecher** [JellyBitz/vSRO-ServerAddon#4]
If i kill some unique on maps that GameServer-1 load, the kill message don't appear on GameServer-2 maps. This only happens when UNIQUE_LOGS is active.

Sorry for my bad english, i learning by myself ;)

**Comment by JellyBitz** [comment]
UNIQUE_LOGS doesn't have any restriction. If the message doesn't appear in the Gameserver N°2, it's because it's not receiving any message about it, as simple as that.
