### ISSUE TITLE
Mutate Item

### ISSUE THREAD

**Issue by gaffag** [JellyBitz/vSRO-ServerAddon#6]
Hello bro, i have only one question..
why item mutation is not working on inventory slots from 0 to 12 ?
Thanks

**Comment by JellyBitz** [comment]
I never saw an item changing on these slots originally.
Game design probably, or some extra check preventing that behavior.

**Comment by gaffag** [comment]
aha, i think they want to avoid bugs.. because if its not wearable item or different gender, it will cause bug in character.
Thanks bro , and also thanks for your great work)))
